### PR TITLE
Bust CDN cache after updating files

### LINKED ISSUE #68: Nightly appliance/container build fails due to yum repo's CDN cache
Moving gitter conversion to issue.

Nightly build for container images have been failing often with errors like this:
```
Errors during downloading metadata for repository 'manageiq-11-kasparov'.
```
The container build hits yum repo 5 min or so after rpm build/upload is completed and it looks some files are not updated/sync'ed at that time. The log shows it was trying to access primary.xml.gz from the day before (which is gone since that day's nightly already updated that fie).

Based on the gitter conversion, this is probably that the CDN cache hasn't been refreshed yet.

### PR DESCRIPTION
**Pull request by bdunne**
Depends on: #69 
Fixes #68

### CODE REVIEW

File: lib/manageiq/rpm_build/rpm_repo.rb [hunk 1]
```diff
@@ -70,6 +71,15 @@ def update
               client.delete_object(:bucket => OPTIONS.rpm_repository.s3_api.bucket, :key => object.key)
             end
           end
+
+          # Bust the cache for updated files
+          if OPTIONS.rpm_repository.digitalocean_access_token
+            puts "Purging the cache for files that were uploaded"
+            require 'droplet_kit'
```
Comment (Fryguy) [inline lib/manageiq/rpm_build/rpm_repo.rb:78]: @bdunne I just realized this isn't in the Gemfile...is that intentional?

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit a58b4ed88b2d26f63eb4d4e6065d3e83dbc7ef83
Author: Jason Frey <fryguy9@gmail.com>
Date:   Thu Jun 25 12:49:36 2020 -0400

    Merge pull request #71 from bdunne/bust_cache

    Bust CDN cache after updating files

    (cherry picked from commit 88217f4a2e8fafeb98cc0a15549543299e598056)
```

File: lib/manageiq/rpm_build/rpm_repo.rb (hunk 1 above)
Comment (bdunne) [reply lib/manageiq/rpm_build/rpm_repo.rb:78]: No, apparently I forgot to save the Gemfile change... https://github.com/ManageIQ/manageiq-rpm_build/pull/72
